---
- name: this is for test
  hosts: dev
  become: true
  gather_facts: yes
  tasks:
    - name: code deploy
      ansible.builtin.git:
    	repo: https://github.com/TejasGowda5476/ansible-code-deploy.git
    	dest: /var/www/html
    	single_branch: yes
    	version: main
